class TypedArgs:
    dataset: str
    data_location: list[str]
    trajec_max_len: int
    start_n: int
    n_span: int
    trajec_max_len_valid: int
    start_n_valid: int
    n_span_valid: int
    n_layer: int
    output_hidden_states: bool
    output_attentions: bool
    n_ctx: int
    n_embd: int
    n_head: int
    embd_pdrop: float
    layer_norm_epsilon: float
    attn_pdrop: float
    resid_pdrop: float
    activation_function: str
    initializer_range: float
    start_Nt: int
    d_Nt: int
    batch_size: int
    batch_size_valid: int
    shuffle: bool
    device: str
    epoch_num: int
    learning_rate: float
    gamma: float
    coarse_dim: list[int]
    coarse_mode: str
    march_tol: float
    # Dynamically added attributes
    time: str
    dir_output: str
    fname: str
    experiment_path: str
    model_save_path: str
    logging_path: str
    current_model_save_path: str
    logging_epoch_path: str
